# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'color.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

import os
from PyQt5 import QtCore, QtGui, QtWidgets

logotop = os.path.split(os.path.realpath(__file__))[0]
logotop_x = os.path.join(logotop,"logo.ico")

class Ui_Colorwindow(object):
    def setupUi(self, Colorwindow):
        Colorwindow.setObjectName("Colorwindow")
        Colorwindow.resize(640, 450)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(logotop_x), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Colorwindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Colorwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.b7 = QtWidgets.QVBoxLayout()
        self.b7.setSpacing(0)
        self.b7.setObjectName("b7")
        self.a6 = QtWidgets.QHBoxLayout()
        self.a6.setObjectName("a6")
        self.b8 = QtWidgets.QGroupBox(self.centralwidget)
        self.b8.setObjectName("b8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.b8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.a7 = QtWidgets.QHBoxLayout()
        self.a7.setContentsMargins(-1, 26, -1, 27)
        self.a7.setObjectName("a7")
        self.YT = QtWidgets.QLabel(self.b8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YT.sizePolicy().hasHeightForWidth())
        self.YT.setSizePolicy(sizePolicy)
        self.YT.setMinimumSize(QtCore.QSize(280, 210))
        self.YT.setText("")
        self.YT.setAlignment(QtCore.Qt.AlignCenter)
        self.YT.setObjectName("YT")
        self.a7.addWidget(self.YT)
        self.verticalLayout.addLayout(self.a7)
        self.a6.addWidget(self.b8)
        self.b9 = QtWidgets.QGroupBox(self.centralwidget)
        self.b9.setObjectName("b9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.b9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.a8 = QtWidgets.QHBoxLayout()
        self.a8.setContentsMargins(-1, 26, -1, 27)
        self.a8.setObjectName("a8")
        self.SC = QtWidgets.QLabel(self.b9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SC.sizePolicy().hasHeightForWidth())
        self.SC.setSizePolicy(sizePolicy)
        self.SC.setMinimumSize(QtCore.QSize(280, 210))
        self.SC.setText("")
        self.SC.setAlignment(QtCore.Qt.AlignCenter)
        self.SC.setObjectName("SC")
        self.a8.addWidget(self.SC)
        self.verticalLayout_2.addLayout(self.a8)
        self.a6.addWidget(self.b9)
        self.b7.addLayout(self.a6)
        self.b10 = QtWidgets.QVBoxLayout()
        self.b10.setObjectName("b10")
        self.a9 = QtWidgets.QHBoxLayout()
        self.a9.setContentsMargins(10, -1, -1, -1)
        self.a9.setObjectName("a9")
        self.HRB = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.HRB.setFont(font)
        self.HRB.setObjectName("HRB")
        self.a9.addWidget(self.HRB)
        spacerItem = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.a9.addItem(spacerItem)
        self.b11 = QtWidgets.QVBoxLayout()
        self.b11.setObjectName("b11")
        self.LHRH = QtWidgets.QSlider(self.centralwidget)
        self.LHRH.setMaximum(255)
        self.LHRH.setOrientation(QtCore.Qt.Horizontal)
        self.LHRH.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.LHRH.setObjectName("LHRH")
        self.b11.addWidget(self.LHRH)
        self.a9.addLayout(self.b11)
        self.a10 = QtWidgets.QHBoxLayout()
        self.a10.setContentsMargins(5, 0, 5, 0)
        self.a10.setObjectName("a10")
        self.LHRB = QtWidgets.QLabel(self.centralwidget)
        self.LHRB.setObjectName("LHRB")
        self.a10.addWidget(self.LHRB)
        self.a9.addLayout(self.a10)
        self.b12 = QtWidgets.QVBoxLayout()
        self.b12.setObjectName("b12")
        self.HHRH = QtWidgets.QSlider(self.centralwidget)
        self.HHRH.setMaximum(255)
        self.HHRH.setPageStep(10)
        self.HHRH.setProperty("value", 255)
        self.HHRH.setTracking(True)
        self.HHRH.setOrientation(QtCore.Qt.Horizontal)
        self.HHRH.setInvertedAppearance(False)
        self.HHRH.setInvertedControls(False)
        self.HHRH.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.HHRH.setObjectName("HHRH")
        self.b12.addWidget(self.HHRH)
        self.a9.addLayout(self.b12)
        self.a11 = QtWidgets.QHBoxLayout()
        self.a11.setContentsMargins(5, 0, 5, 0)
        self.a11.setObjectName("a11")
        self.HHRB = QtWidgets.QLabel(self.centralwidget)
        self.HHRB.setObjectName("HHRB")
        self.a11.addWidget(self.HHRB)
        self.a9.addLayout(self.a11)
        self.a9.setStretch(0, 1)
        self.a9.setStretch(1, 1)
        self.a9.setStretch(2, 8)
        self.a9.setStretch(3, 3)
        self.a9.setStretch(4, 8)
        self.a9.setStretch(5, 3)
        self.b10.addLayout(self.a9)
        self.a12 = QtWidgets.QHBoxLayout()
        self.a12.setContentsMargins(10, -1, -1, -1)
        self.a12.setObjectName("a12")
        self.SGB = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SGB.setFont(font)
        self.SGB.setObjectName("SGB")
        self.a12.addWidget(self.SGB)
        spacerItem1 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.a12.addItem(spacerItem1)
        self.b13 = QtWidgets.QVBoxLayout()
        self.b13.setObjectName("b13")
        self.LSGH = QtWidgets.QSlider(self.centralwidget)
        self.LSGH.setMaximum(255)
        self.LSGH.setOrientation(QtCore.Qt.Horizontal)
        self.LSGH.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.LSGH.setObjectName("LSGH")
        self.b13.addWidget(self.LSGH)
        self.a12.addLayout(self.b13)
        self.a13 = QtWidgets.QHBoxLayout()
        self.a13.setContentsMargins(5, 0, 5, 0)
        self.a13.setSpacing(6)
        self.a13.setObjectName("a13")
        self.LSGB = QtWidgets.QLabel(self.centralwidget)
        self.LSGB.setObjectName("LSGB")
        self.a13.addWidget(self.LSGB)
        self.a12.addLayout(self.a13)
        self.b14 = QtWidgets.QVBoxLayout()
        self.b14.setObjectName("b14")
        self.HSGH = QtWidgets.QSlider(self.centralwidget)
        self.HSGH.setMaximum(255)
        self.HSGH.setProperty("value", 255)
        self.HSGH.setOrientation(QtCore.Qt.Horizontal)
        self.HSGH.setInvertedAppearance(False)
        self.HSGH.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.HSGH.setTickInterval(0)
        self.HSGH.setObjectName("HSGH")
        self.b14.addWidget(self.HSGH)
        self.a12.addLayout(self.b14)
        self.a14 = QtWidgets.QHBoxLayout()
        self.a14.setContentsMargins(5, 0, 5, 0)
        self.a14.setObjectName("a14")
        self.HSGB = QtWidgets.QLabel(self.centralwidget)
        self.HSGB.setObjectName("HSGB")
        self.a14.addWidget(self.HSGB)
        self.a12.addLayout(self.a14)
        self.a12.setStretch(0, 1)
        self.a12.setStretch(1, 1)
        self.a12.setStretch(2, 8)
        self.a12.setStretch(3, 3)
        self.a12.setStretch(4, 8)
        self.a12.setStretch(5, 3)
        self.b10.addLayout(self.a12)
        self.a15 = QtWidgets.QHBoxLayout()
        self.a15.setContentsMargins(10, -1, -1, -1)
        self.a15.setObjectName("a15")
        self.VBB = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.VBB.setFont(font)
        self.VBB.setObjectName("VBB")
        self.a15.addWidget(self.VBB)
        spacerItem2 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.a15.addItem(spacerItem2)
        self.b15 = QtWidgets.QVBoxLayout()
        self.b15.setObjectName("b15")
        self.LVBH = QtWidgets.QSlider(self.centralwidget)
        self.LVBH.setMaximum(255)
        self.LVBH.setOrientation(QtCore.Qt.Horizontal)
        self.LVBH.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.LVBH.setObjectName("LVBH")
        self.b15.addWidget(self.LVBH)
        self.a15.addLayout(self.b15)
        self.a16 = QtWidgets.QHBoxLayout()
        self.a16.setContentsMargins(5, 0, 5, 0)
        self.a16.setObjectName("a16")
        self.LVBB = QtWidgets.QLabel(self.centralwidget)
        self.LVBB.setObjectName("LVBB")
        self.a16.addWidget(self.LVBB)
        self.a15.addLayout(self.a16)
        self.b16 = QtWidgets.QVBoxLayout()
        self.b16.setObjectName("b16")
        self.HVBH = QtWidgets.QSlider(self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.HVBH.setFont(font)
        self.HVBH.setTabletTracking(False)
        self.HVBH.setMaximum(255)
        self.HVBH.setProperty("value", 255)
        self.HVBH.setTracking(True)
        self.HVBH.setOrientation(QtCore.Qt.Horizontal)
        self.HVBH.setInvertedAppearance(False)
        self.HVBH.setInvertedControls(False)
        self.HVBH.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.HVBH.setTickInterval(0)
        self.HVBH.setObjectName("HVBH")
        self.b16.addWidget(self.HVBH)
        self.a15.addLayout(self.b16)
        self.a17 = QtWidgets.QHBoxLayout()
        self.a17.setContentsMargins(5, 0, 5, 0)
        self.a17.setObjectName("a17")
        self.HVBB = QtWidgets.QLabel(self.centralwidget)
        self.HVBB.setObjectName("HVBB")
        self.a17.addWidget(self.HVBB)
        self.a15.addLayout(self.a17)
        self.a15.setStretch(0, 1)
        self.a15.setStretch(1, 1)
        self.a15.setStretch(2, 8)
        self.a15.setStretch(3, 3)
        self.a15.setStretch(4, 8)
        self.a15.setStretch(5, 3)
        self.b10.addLayout(self.a15)
        self.b7.addLayout(self.b10)
        self.a18 = QtWidgets.QHBoxLayout()
        self.a18.setContentsMargins(0, 0, -1, 0)
        self.a18.setSpacing(6)
        self.a18.setObjectName("a18")
        self.WCSCAN = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WCSCAN.sizePolicy().hasHeightForWidth())
        self.WCSCAN.setSizePolicy(sizePolicy)
        self.WCSCAN.setIconSize(QtCore.QSize(16, 16))
        self.WCSCAN.setObjectName("WCSCAN")
        self.a18.addWidget(self.WCSCAN)
        self.b7.addLayout(self.a18)
        self.b7.setStretch(0, 8)
        self.b7.setStretch(1, 2)
        self.gridLayout.addLayout(self.b7, 0, 0, 1, 1)
        Colorwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Colorwindow)
        QtCore.QMetaObject.connectSlotsByName(Colorwindow)

    def retranslateUi(self, Colorwindow):
        _translate = QtCore.QCoreApplication.translate
        Colorwindow.setWindowTitle(_translate("Colorwindow", "Threshold"))
        self.b8.setTitle(_translate("Colorwindow", "原始图像 "))
        self.b9.setTitle(_translate("Colorwindow", "阈值图像 "))
        self.HRB.setText(_translate("Colorwindow", "H / R"))
        self.LHRB.setText(_translate("Colorwindow", "min:0"))
        self.HHRB.setText(_translate("Colorwindow", "max:255"))
        self.SGB.setText(_translate("Colorwindow", "S / G"))
        self.LSGB.setText(_translate("Colorwindow", "min:0"))
        self.HSGB.setText(_translate("Colorwindow", "max:255"))
        self.VBB.setText(_translate("Colorwindow", "V / B"))
        self.LVBB.setText(_translate("Colorwindow", "min:0"))
        self.HVBB.setText(_translate("Colorwindow", "max:255"))
        self.WCSCAN.setText(_translate("Colorwindow", "返回"))

